/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/common/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    BookingForm: typeof import('./src/components/booking/BookingForm.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MovieCard: typeof import('./src/components/movie/MovieCard.vue')['default']
    MovieList: typeof import('./src/components/movie/MovieList.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeatSelector: typeof import('./src/components/booking/SeatSelector.vue')['default']
    TransactionList: typeof import('./src/components/wallet/TransactionList.vue')['default']
    WalletBalance: typeof import('./src/components/wallet/WalletBalance.vue')['default']
  }
}
